import { Match } from '../types';

export const walkOverData: Match[] = [
  {
    id: 260005,
    name: 'Final - Match',
    nextMatchId: null,
    nextLooserMatchId: null,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'c016cb2a-fdd9-4c40-a81f-0cc6bdf4b9cc',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'giacomo123',
      },
      {
        id: '9ea9ce1a-4794-4553-856c-9a3620c0531b',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Ant',
      },
    ],
  },
  {
    id: 260006,
    name: 'Semi Final - Match 1',
    nextMatchId: 260005,
    nextLooserMatchId: null,
    tournamentRoundText: '3',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'c016cb2a-fdd9-4c40-a81f-0cc6bdf4b9cc',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'giacomo123',
      },
      {
        id: '008de019-4af6-4178-a042-936c33fea3e9',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TowbyTest',
      },
    ],
  },
  {
    id: 260013,
    name: 'Semi Final - Match 2',
    nextMatchId: 260005,
    nextLooserMatchId: null,
    tournamentRoundText: '3',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '9c92feb3-4aa4-4475-a34e-f9a200e21aa9',
        resultText: null,
        isWinner: false,
        status: 'NO_SHOW',
        name: 'WubbaLubbaDubbish',
      },
      {
        id: '9ea9ce1a-4794-4553-856c-9a3620c0531b',
        resultText: null,
        isWinner: true,
        status: 'WALK_OVER',
      },
    ],
  },
  {
    id: 260007,
    name: 'Round 2 - Match 1',
    nextMatchId: 260006,
    nextLooserMatchId: null,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '1ec356ec-a7c4-4026-929b-3657286a92d8',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'TestSpectacles',
      },
      {
        id: 'c016cb2a-fdd9-4c40-a81f-0cc6bdf4b9cc',
        resultText: '0',
        isWinner: true,
        status: 'PLAYED',
      },
    ],
  },
  {
    id: 260010,
    name: 'Round 2 - Match 2',
    nextMatchId: 260006,
    nextLooserMatchId: null,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'c2f551b4-2d5a-4c59-86a8-df575805256a',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'Ahshitherewegoagain',
      },
      {
        id: '008de019-4af6-4178-a042-936c33fea3e9',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
      },
    ],
  },
  {
    id: 260014,
    name: 'Round 2 - Match 3',
    nextMatchId: 260013,
    nextLooserMatchId: null,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '9c92feb3-4aa4-4475-a34e-f9a200e21aa9',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
      },
      {
        id: '4651dcd0-853e-4242-9924-602e8200dd17',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'FIFA_MASTER',
      },
    ],
  },
  {
    id: 260017,
    name: 'Round 2 - Match 4',
    nextMatchId: 260013,
    nextLooserMatchId: null,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '9ea9ce1a-4794-4553-856c-9a3620c0531b',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
      },
      {
        id: '76ac9113-a541-4b6a-a189-7b5ad43729bd',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'رئيس',
      },
    ],
  },
  {
    id: 260011,
    name: 'Round 1 - Match 3',
    nextMatchId: 260010,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: 'c2f551b4-2d5a-4c59-86a8-df575805256a',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260009,
    name: 'Round 1 - Match 2',
    nextMatchId: 260007,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '1ec356ec-a7c4-4026-929b-3657286a92d8',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260008,
    name: 'Round 1 - Match 1',
    nextMatchId: 260007,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'c016cb2a-fdd9-4c40-a81f-0cc6bdf4b9cc',
        resultText: '1',
        isWinner: true,
        status: 'PLAYED',
        name: 'giacomo123',
      },
      {
        id: '4831deb3-969b-49e1-944e-3ad886e6dd6c',
        resultText: '0',
        isWinner: false,
        status: 'PLAYED',
        name: 'ZoeZ',
      },
    ],
  },
  {
    id: 260015,
    name: 'Round 1 - Match 5',
    nextMatchId: 260014,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '9c92feb3-4aa4-4475-a34e-f9a200e21aa9',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260012,
    name: 'Round 1 - Match 4',
    nextMatchId: 260010,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '008de019-4af6-4178-a042-936c33fea3e9',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260019,
    name: 'Round 1 - Match 8',
    nextMatchId: 260017,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '76ac9113-a541-4b6a-a189-7b5ad43729bd',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260018,
    name: 'Round 1 - Match 7',
    nextMatchId: 260017,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '9ea9ce1a-4794-4553-856c-9a3620c0531b',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
  {
    id: 260016,
    name: 'Round 1 - Match 6',
    nextMatchId: 260014,
    nextLooserMatchId: null,
    tournamentRoundText: '1',
    startTime: null,
    state: 'WALK_OVER',
    participants: [
      {
        id: '4651dcd0-853e-4242-9924-602e8200dd17',
        resultText: null,
        isWinner: false,
        status: null,
      },
    ],
  },
];

export const simpleSmallBracket: Match[] = [
  {
    id: 19753,
    nextMatchId: null,
    tournamentRoundText: '3',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19754,
    nextMatchId: 19753,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: '14754a1a-932c-4992-8dec-f7f94a339960',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'CoKe BoYz',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19755,
    nextMatchId: 19754,
    tournamentRoundText: '1',
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '14754a1a-932c-4992-8dec-f7f94a339960',
        resultText: 'Won',
        isWinner: true,
        status: 'PLAYED',
        name: 'CoKe BoYz',
        picture: 'teamlogos/client_team_default_logo',
      },
      {
        id: 'd16315d4-7f2d-427b-ae75-63a1ae82c0a8',
        resultText: 'Lost',
        isWinner: false,
        status: 'PLAYED',
        name: 'Aids Team',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19756,
    nextMatchId: 19754,
    tournamentRoundText: '1',
    startTime: '2021-05-30',
    state: 'RUNNING',
    participants: [
      {
        id: 'd8b9f00a-0ffa-4527-8316-da701894768e',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Art of kill',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19757,
    nextMatchId: 19753,
    tournamentRoundText: '2',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19758,
    nextMatchId: 19757,
    tournamentRoundText: '1',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: '9397971f-4b2f-44eb-a094-722eb286c59b',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Crazy Pepes',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19759,
    nextMatchId: 19757,
    tournamentRoundText: '1',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: '42fecd89-dc83-4821-80d3-718acb50a30c',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'BLUEJAYS',
        picture: 'teamlogos/client_team_default_logo',
      },
      {
        id: 'df01fe2c-18db-4190-9f9e-aa63364128fe',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Bosphorus',
        picture: 'teamlogos/r7zn4gr8eajivapvjyzd',
      },
    ],
  },
  {
    id: 19760,
    nextMatchId: 19756,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19768,
    nextMatchId: 19760,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19769,
    nextMatchId: 19760,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19761,
    nextMatchId: 19756,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19770,
    nextMatchId: 19761,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19771,
    nextMatchId: 19761,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19762,
    nextMatchId: 19755,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19772,
    nextMatchId: 19762,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19773,
    nextMatchId: 19762,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19763,
    nextMatchId: 19755,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19774,
    nextMatchId: 19763,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19775,
    nextMatchId: 19763,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19764,
    nextMatchId: 19758,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19776,
    nextMatchId: 19764,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19777,
    nextMatchId: 19764,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19765,
    nextMatchId: 19758,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19778,
    nextMatchId: 19765,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19779,
    nextMatchId: 19765,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19766,
    nextMatchId: 19759,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19780,
    nextMatchId: 19766,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19781,
    nextMatchId: 19766,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19767,
    nextMatchId: 19759,
    tournamentRoundText: '4',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19782,
    nextMatchId: 19767,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19783,
    nextMatchId: 19767,
    tournamentRoundText: '5',
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
];

export const simpleBracket: Match[] =   [
  {
      "id": 9,
      "nextMatchId": null,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 5",
              "picture": null,
              "winner": false
          },
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 6",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 9,
          "fixtureStage": "For Position 1 to 2",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": null,
          "firstTeamName": "Winner of match 5",
          "firstTeamPrevMathchNo": 5,
          "secondRegistrationId": null,
          "secondTeamName": "Winner of match 6",
          "secondTeamPrevMathchNo": 6,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 6,
      "nextMatchId": 9,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 3",
              "picture": null,
              "winner": false
          },
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 4",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 6,
          "fixtureStage": "For Position 1 to 4",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": null,
          "firstTeamName": "Winner of match 3",
          "firstTeamPrevMathchNo": 3,
          "secondRegistrationId": null,
          "secondTeamName": "Winner of match 4",
          "secondTeamPrevMathchNo": 4,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 5,
      "nextMatchId": 9,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 1",
              "picture": null,
              "winner": false
          },
          {
              "id": null,
              "resultText": null,
              "status": null,
              "name": "Winner of match 2",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 5,
          "fixtureStage": "For Position 1 to 4",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": null,
          "firstTeamName": "Winner of match 1",
          "firstTeamPrevMathchNo": 1,
          "secondRegistrationId": null,
          "secondTeamName": "Winner of match 2",
          "secondTeamPrevMathchNo": 2,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 4,
      "nextMatchId": 6,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": "-7",
              "resultText": null,
              "status": null,
              "name": "Participant 7",
              "picture": null,
              "winner": false
          },
          {
              "id": "-8",
              "resultText": null,
              "status": null,
              "name": "Participant 8",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 4,
          "fixtureStage": "For Position 1 to 8",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": -7,
          "firstTeamName": "Participant 7",
          "firstTeamPrevMathchNo": null,
          "secondRegistrationId": -8,
          "secondTeamName": "Participant 8",
          "secondTeamPrevMathchNo": null,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 3,
      "nextMatchId": 6,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": "-5",
              "resultText": null,
              "status": null,
              "name": "Participant 5",
              "picture": null,
              "winner": false
          },
          {
              "id": "-6",
              "resultText": null,
              "status": null,
              "name": "Participant 6",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 3,
          "fixtureStage": "For Position 1 to 8",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": -5,
          "firstTeamName": "Participant 5",
          "firstTeamPrevMathchNo": null,
          "secondRegistrationId": -6,
          "secondTeamName": "Participant 6",
          "secondTeamPrevMathchNo": null,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 2,
      "nextMatchId": 5,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": "-3",
              "resultText": null,
              "status": null,
              "name": "Participant 3",
              "picture": null,
              "winner": false
          },
          {
              "id": "-4",
              "resultText": null,
              "status": null,
              "name": "Participant 4",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 2,
          "fixtureStage": "For Position 1 to 8",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": -3,
          "firstTeamName": "Participant 3",
          "firstTeamPrevMathchNo": null,
          "secondRegistrationId": -4,
          "secondTeamName": "Participant 4",
          "secondTeamPrevMathchNo": null,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  },
  {
      "id": 1,
      "nextMatchId": 5,
      "tournamentRoundText": "For Position 1 to 2",
      "startTime": null,
      "state": null,
      "participants": [
          {
              "id": "-1",
              "resultText": null,
              "status": null,
              "name": "Participant 1",
              "picture": null,
              "winner": false
          },
          {
              "id": "-2",
              "resultText": null,
              "status": null,
              "name": "Participant 2",
              "picture": null,
              "winner": false
          }
      ],
      "fixture": {
          "fixtureId": null,
          "matchNo": 1,
          "fixtureStage": "For Position 1 to 8",
          "groupId": null,
          "groupName": null,
          "firstRegistrationId": -1,
          "firstTeamName": "Participant 1",
          "firstTeamPrevMathchNo": null,
          "secondRegistrationId": -2,
          "secondTeamName": "Participant 2",
          "secondTeamPrevMathchNo": null,
          "fixtureDate": null,
          "venueId": null,
          "tournamentCategoryId": null,
          "matchScore": null,
          "createdBy": null,
          "updatedBy": null,
          "createdDate": null,
          "updatedDate": null,
          "tournamentMatchDetailList": null,
          "tournamentFixtureId": null,
          "connectedMatchId": null,
          "firstCompanyId": null,
          "secondCompanyId": null,
          "firstTeamPlayerId": null,
          "secondTeamPlayerId": null,
          "firstPlayer1stId": null,
          "firstPlayer2ndId": null,
          "secondPlayer1stId": null,
          "secondPlayer2ndId": null,
          "venues": null,
          "courtInfo": null,
          "matchOfficials": null
      }
  }
];
